version: '3'

services:
  reflex-backend:
    #    image: ghcr.io/luler/reflex_ai_fast-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./uploaded_files:/app/uploaded_files
#    ports:
#      - 8000:8000
#    env_file:
#      - .env
#    environment:
#      - OPENAI_BASE_URL=
#      - OPENAI_API_KEY=

  reflex-frontend:
    #    image: ghcr.io/luler/reflex_ai_fast-web:latest
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
      - 8080:80
#    env_file:
#      - .env
